### ISSUE TITLE
v3.0.3 breaking changes

### ISSUE THREAD

**Issue by TSteele27** [madebysource/lesshat#170]
With the latest release of lesshat you removed the build folder from the npm package. This breaks integrations that were expecting the prebuilt version of lesshat to exist. I would expect a change like this to come as a major version change not a patch version change.

**Comment by mboudreau** [comment]
Crap, my bad.  That definitely shouldn't be the case.  Deployment teething
issues.  I'll unpublish this version and create a new one.

**Comment by mboudreau** [comment]
Yeah, after some thought, since the deployment hasn't gone out in so long, there is going to be some risk involved.  I'll update the version number to 4.0.0 so it shouldn't affect any builds and people can proceed at their own risk.

**Comment by rmunson** [comment]
@mboudreau So this issues is closed now, as 4.x takes over this change... but I'm curious, what is the end-game of removing the build directory?  
Should everyone using lesshat now have a an additional build step for dev?  

Or is the plan to include the build folder in future tags (which seems to make the most sense)?

If you are cutting a release, shouldn't it contain built files?

**Comment by mboudreau** [comment]
Generated files should never be part of the source. The whole point of a
release is to generate these files and deploy them into an artifact. This
is what npm is for.

If you're using bower, I strongly recommend to move away from it since it
breeds bad practices. If you really have to use bower, you can always point
it to the npm zip file for that particular version.

Hope that answers your question.

M

**Comment by rmunson** [comment]
While I generally agree with you re: generated files and source, lesshat is a bit of a different animal.  The output of the project is source code (less files), not a stand-alone deployable.

Looks like you've dropped support for bower altogether for 4.x+.  It would be nice if there was a statement to that affect in the Readme or on lesshat.com, especially since the bower registry will continue to point users at newly tagged versions.

**Comment by mboudreau** [comment]
Not a bad idea.  I'll get to it tonight.

**Comment by mboudreau** [comment]
@rmunson sorry for taking a while to get to this. I've added instructions about how to use bower in the new method.

Cheers.
