### ISSUE TITLE
removal of build folder from master

### ISSUE THREAD

**Issue by leviwheatcroft** [madebysource/lesshat#171]
was this intended? The folder is still listed in the README.md on master.

I note that @mboudreau mentioned improving the version release process in issue #162 on the same day that change commit 5a76519379902c8710302c916e29eabfff4f2a30 was merged to master, so maybe this change was intended?

I'm a novice.. but does this mean I'd have to build lesshat after installing the npm package? That would be an unusual approach compared to other modules containing browser assets.

**Comment by longzheng** [comment]
+1

**Comment by Loord86** [comment]
+1

**Comment by mboudreau** [comment]
Yes, this is intended.  Sorry that I haven't removed it from the README yet.  I'll do that right now.

The whole point of using NPM is to simply package the artifacts from the build process, which in this case is the compiled less file.  In Lesshat 4.0, there is no more 'build' folder within the npm package.  The less file is now available on the root of your package (it should be node_modules/lesshat/lesshat.less).

If you're using npm, *you do not need to build the files after the case*.  You couldn't even if you wanted to  because the source files aren't included within the npm package.

Hope that fixes that for you.  If you have any other questions, please ask away on this thread.

Cheers.
