### ISSUE TITLE
Download url https://raw.githubusercontent.com/csshat/lesshat/master/build/lesshat.less is invalid

### ISSUE THREAD

**Issue by aukgit** [madebysource/lesshat#172]
Download url https://raw.githubusercontent.com/csshat/lesshat/master/build/lesshat.less is invalid

**Comment by longzheng** [comment]
+1

**Comment by Loord86** [comment]
+1

**Comment by mboudreau** [comment]
That is correct.  I've removed the build folder from github because compiled code doesn't belong on github because it's not made for it.  The artifacts created from [our continuous integration server](https://travis-ci.org/madebysource/lesshat) are deployed to NPM which is [much better to manage versioning than say bower](https://medium.com/@nickheiner/why-my-team-uses-npm-instead-of-bower-eecfe1b9afcb).  I find bower to be kind of redundant since you're already using npm to install bower in the first place.

If you are still adamant on bower, you can always point your dependency to the versioned tarball on NPM within your bower.json like this:

```
"dependencies": {
    "lesshat": "https://registry.npmjs.org/lesshat/-/lesshat-4.0.1.tgz"
}
``` 

Or you can achieve the same thing by running this command in your application folder:

`bower install lesshat=https://registry.npmjs.org/lesshat/-/lesshat-4.0.1.tgz --save`

It will not automatically update to a new fix version via semantic versioning since the compressed file is explicit.  

I hope that this fixes your problem.  If there's any other questions, please add them to this thread.  I'll update the readme with this information.

Cheers.

**Comment by aukgit** [comment]
Thank you.

**Comment by mboudreau** [comment]
@aukgit You're very welcome.
